### ISSUE TITLE
Possible typo in the paper

### ISSUE THREAD

**Issue by wangyirui** [dvl-tum/motsynth-baselines#3]
Thanks for sharing MOTSynth dataset and the corresponding code! 

I have one minor comment for the paper.  On paper P7 section 4.4. Multi-object Tracking left-column Results paragraph, the paper says "we obtain _45.0 MOTA_ and 51.2 IDF1 with our MOTSynth trained model, yielding **+3.5 MOTA** and +1.6 IDF1 improvement over the COCO trained model (_43.5 MOTA_ and 49.6 IDF1).". Does it seem the improvement on MOTA should be +1.5 MOTA?

Thank you!

**Comment by guillembraso** [comment]
Hi, thanks for your interest in our paper!

You're right about the typo, good catch! We will update the text in a future arXiv update.

Thanks again,

Guillem
