### ISSUE TITLE
YOLOv3 settings

### ISSUE THREAD

**Issue by wangyirui** [dvl-tum/motsynth-baselines#4]
Could you please provide more details regarding the YOLOv3 baseline? 

Since most of the common configurations (e.g., YOLOv3-tiny, YOLOv3, YOLOv3-SPP, YOLOv3-SPP-ultralytics) all accept the input size of 608.

Thank you in advance!

**Comment by guillembraso** [comment]
Hi,

I did not run these experiments, so I've asked about them. You should get an update soon!

**Comment by wangyirui** [comment]
> Hi,
> 
> I did not run these experiments, so I've asked about them. You should get an update soon!

Much appreciated!

**Comment by fabbrimatteo** [comment]
Hi,

We used the classic YOLOv3 configuration, changing the output classes to 1.

**Comment by wangyirui** [comment]
Thank you Matteo!


Best,
Yirui
