### ISSUE TITLE
Question about the data and submission info

### ISSUE THREAD

**Issue by SangbumChoi** [dvl-tum/motsynth-baselines#8]
Hi, I have two questions about this MOTSynth challenge
1. After following data preparing process as following site mot annotations has starting from repo '000'.
![image](https://user-images.githubusercontent.com/34004152/160347450-9dab3794-8aef-4e79-8d77-2864a7b396cf.png)
However, extracted frames from original zip file is starting from '003', so what am I missing in this stage? It looks like wget code suppose to get zip file from sequence including '000'.
![image](https://user-images.githubusercontent.com/34004152/160347583-4c132597-ba9c-4e93-83b8-70dbb1189daa.png)
> https://github.com/dvl-tum/motsynth-baselines/blob/main/docs/DATA_PREPARATION.md 
2. According to evaluation server, it suppose to add not only MOT17-test.txt but also MOTSynth.txt. Can't we just submit MOT17-test.txt for saving time? (because evaluation also takes one-hour or more for only MOT17)
![image](https://user-images.githubusercontent.com/34004152/160347857-72f795a1-e7c6-4a89-b5ac-d4c23b91566c.png)

Thanks

**Comment by markweberdev** [comment]
Hi,

regarding your 2nd question, yes you only need to submit the MOT txt files. We already implemented it that way, but forgot to change the public instructions. Thanks for pointing that out! If that doesn't work, please let us know.

Best,
Mark

**Comment by guillembraso** [comment]
Hi,

I have double-checked again the video zip files, and they do contain all of the videos, starting at 000.mp4. I've also double-checked the `to_frames.py` script and it works fine. Can you please double-check whether you downloaded and extracted all the MOTSynth parts correctly?

I can also see from your screenshot that you're missing many more videos (004, 007, 012, etc.)

Best,

Guillem

**Comment by SangbumChoi** [comment]
@markweberdev Thanks okay
@guillembraso Sorry for my mistake during downloading MOTSynth my connection seems disconnected. I will close this issue
