### ISSUE TITLE
Camera coordinates in the MOTSynth dataset

### ISSUE THREAD

**Issue by wangyirui** [dvl-tum/motsynth-baselines#9]
In the annotation file, I noticed that there are two fields named "cam_world_pos" and "cam_world_rot",  what are the typical use cases of these two parameters? If there are any examples or explanations, that would be greatly appreciated. Thank you!

**Comment by fabbrimatteo** [comment]
Hi! The camera position and rotation can be especially useful where the camera moves. In those cases the two fields can be used for visual odometry appliacations, egomotion, and 3D reconstruction.

**Comment by wangyirui** [comment]
> Hi! The camera position and rotation can be especially useful where the camera moves. In those cases the two fields can be used for visual odometry appliacations, egomotion, and 3D reconstruction.

Thanks for your reply and the insights on it!
